name: Node.js CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.19.1
      - run: npm install
      - run: npm run build --if-present
      - run: node app.js
